- hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Deploy Nginx SSL proxy config
      template:
        src: nginx-proxy.conf.j2
        dest: /etc/nginx/sites-available/default
        mode: '0644'

    - name: Ensure Nginx is started
      service:
        name: nginx
        state: restarted
